config/routes.rb
Br22Devise::Application.routes.draw do

  resources :creditcard_payments

  resources :creditcard_items

  resources :creditcards

  match "report1" => "reports#report_1", :as => :report_1
  match "report2" => "reports#report_2", :as => :report_2

  resources :categories

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "goto" => "movimentations#goto", :as => :goto

  resources :desires

  match 'overdue' => 'movimentations#overdue', :as => :movimentations_overdue
  match 'all' => 'movimentations#all', :as => :movimentations_all
  resources :movimentations do
    member do
      get 'change_situation'
      get 'change'
      get 'delete'
    end
  end

  match 'token/create' => 'token_authentications#create', :as => :create_token
  match 'token/destroy' => 'token_authentications#destroy', :as => :destroy_token
  devise_for :users, :controllers => { :sessions => "sessions" }

  devise_scope :user do
    get "sign_in", :to => "sessions/create"
    get "sign_out", :to => "sessions/destroy"
  end

  get "home/index"
  get "home/adjust"
  get "home/send_resume_mail", :as => :send_resume_mail

  namespace :android do
    match "login" => "session#login"
    resources :categories
    resources :creditcard_items
    resources :creditcards
    resources :desires
    resources :movimentations
  end

  root :to => "home#welcome"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:send_resume_mail, :welcome]

  def index
  end
  
  def adjust
    @movimentations = Movimentation.all
    @movimentations.each do |movimentation|
      unique_id = UUIDTools::UUID.random_create.to_s
      if movimentation.group_id == "" or movimentation.group_id == nil
        others = Movimentation.where("description = ? AND user_id = ? AND local_to_pay = ? AND group_id = '' ", movimentation.description, movimentation.user_id, movimentation.local_to_pay).all
        others.each do |other|
          other.update_attributes(:group_id => unique_id)
        end
      end
    end
    
    respond_to do |format|
      format.html { }
      format.xml  { head :ok }
    end    
  end
  
  def send_resume_mail
    User.all.each do |user|
      if user.send_resume_mail == true
         MovimentationMailer.resume_email(user).deliver
      end
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @movimentations }
    end
  end

  def welcome
    @user = User.new

    respond_to do |format|
      if current_user == nil
        format.html { render :layout => 'home' }
        format.mobile { render :layout => 'mobile' }
      else
        format.html { redirect_to(movimentations_path, :notice => nil) }
        format.mobile { redirect_to(movimentations_path, :notice => nil) }
      end
      format.xml  { render :xml => @movimentations }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/adjust.html.erb
Contas atualizadas com sucesso.

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/send_resume_mail.html.erb
E-mails com resumo de movimentação enviados com sucesso.

app/views/home/welcome.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="pull-right">
          <%= form_for(@user, :url => session_path(@user), :html => { :class => "form-horizontal" }) do |f| %>
            <b>Acesse sua conta:</b>
            <input class="span3" id="user_email" name="user[email]" size="15" type="email" value="" placeholder="E-mail" required />
            <input class="span2" id="user_password" name="user[password]" size="15" type="password" value="" placeholder="Senha" required/>
            <input id="user_remember_me" name="user[remember_me]" type="checkbox" value="1"/> Lembrar de mim
            <input class="btn btn-primary" id="user_submit" name="commit" type="submit" value="Entrar" />
          <% end %>
      </div>
    </div>
  </div>
  <div class="hero-unit">
    <h1>Controle Financeiro</h1>
    <p>Não perca suas contas de vista, tenha todo o controle sobre suas contas pessoais, cadastre-se agora e começe a organizar suas finanças. Sistema totalmente on-line e gratuito.</p>
    <a class="btn large primary" href="#">Cadastre-se, leva menos de 1 minuto</a>
  </div>
  <div class="row">
    <div class="span7">
      <div class="row">
        <div class="span7">
          <h2>Caracteristicas do Sistema</h2>
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <h4>Gratuito</h4>
          <p>Além de fácil de usar, o controle financeiro é totalmente gratuito.</p>
        </div>
        <div class="span3">
          <h4>Mensal</h4>
          <p>Você terá total controle sobre seus gastos e receitas mês a mês. Visualize de forma fácil suas contas.</p>
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <h4>Alertas</h4>
          <p>Não deixe nada atrasar, receba todos os dias alertas por e-mail.</p>
        </div>
        <div class="span3">
          <h4>Lista de Desejos</h4>
          <p>Cadastre items que você deseja comprar ou serviços que deseja fazer, defina sua prioridade e conquiste seus objetivos</p>
        </div>
      </div>
      <div class="row">
        <div class="span3">
          <h4>Situação da Conta</h4>
          <p>Marque uma conta como recebida ou paga e fique sabendo quanto tem a receber e/ou pagar.</p>
        </div>
        <div class="span3">
          <h4>Tá esperando o quê?</h4>
          <p>Cadastre-se agora mesmo e começe a utilizar o sistema.</p>
        </div>
      </div>
    </div>
    <div class="span4 form-user">
      <div class="row">
        <div class="span4">
          <h2>Não tem cadastro?</h2>
          <p>Cadastre-se preenchendo o formulário abaixo, é rápido e fácil.</p>
        </div>
        <div class="span4">
          <form accept-charset="UTF-8" action="/users?locale=pt-BR" class="user_new form-stacked" id="user_new" method="post">
            <div>
              <label for="user_name">Nome</label>
              <input id="user_name" name="user[name]" size="30" type="text" class="span4" placeholder="Informe seu nome completo" required/>
            </div>
            <div>
              <label for="user_email">E-mail</label>
              <input id="user_email" name="user[email]" size="30" type="email" value="" class="span4" placeholder="Informe seu e-mail" required/>
            </div>
            <div>
              <label for="user_password">Senha</label>
              <input id="user_password" name="user[password]" size="30" type="password" class="span4" placeholder="Informe sua senha" required/>
            </div>
            <div>
              <label for="user_password_confirmation">Confirmação de Senha</label>
              <input id="user_password_confirmation" name="user[password_confirmation]" size="30" type="password" class="span4" placeholder="Repita sua senha para confirmação" required/>
            </div>
            <input id="user_send_resume_mail" name="user[send_resume_mail]" type="hidden" value="false" />
            <div>
              <input class="btn btn-primary" id="user_submit" name="commit" type="submit" value="Cadastrar" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <p>&copy; Controle Financeiro 2011-<%= Time.new.year %> - www.controlefinanceiro.tk <br />Desenvolvido por <a href="http://www.mario-jorge.net" target="_blank">mario-jorge.net</a></p>
  </footer>
</div>

app/views/home/welcome.mobile.erb
<%= form_for(@user, :url => session_path(@user), :html => { 'data-ajax' => "false" }) do |f| %>

<b>Acesse sua conta:</b>

<input class="span3" id="user_email" name="user[email]" size="15" type="email" value="" placeholder="E-mail" required />
<input class="span2" id="user_password" name="user[password]" size="15" type="password" value="" placeholder="Senha" required/>
<label><input id="user_remember_me" name="user[remember_me]" type="checkbox" value="1" />  Lembrar de mim </label>

<input id="user_submit" name="commit" type="submit" value="Entrar" data-theme="b" />
<% end %>