config/routes.rb
Br22Devise::Application.routes.draw do

  resources :creditcard_payments

  resources :creditcard_items

  resources :creditcards

  match "report1" => "reports#report_1", :as => :report_1
  match "report2" => "reports#report_2", :as => :report_2

  resources :categories

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "goto" => "movimentations#goto", :as => :goto

  resources :desires

  match 'overdue' => 'movimentations#overdue', :as => :movimentations_overdue
  match 'all' => 'movimentations#all', :as => :movimentations_all
  resources :movimentations do
    member do
      get 'change_situation'
      get 'change'
      get 'delete'
    end
  end

  match 'token/create' => 'token_authentications#create', :as => :create_token
  match 'token/destroy' => 'token_authentications#destroy', :as => :destroy_token
  devise_for :users, :controllers => { :sessions => "sessions" }

  devise_scope :user do
    get "sign_in", :to => "sessions/create"
    get "sign_out", :to => "sessions/destroy"
  end

  get "home/index"
  get "home/adjust"
  get "home/send_resume_mail", :as => :send_resume_mail

  namespace :android do
    match "login" => "session#login"
    resources :categories
    resources :creditcard_items
    resources :creditcards
    resources :desires
    resources :movimentations
  end

  root :to => "home#welcome"

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :movimentations, :dependent => :nullify

  validates_presence_of :title, :user_id

  def sum_movimentation_by_month_and_year(type, year, month)
    sum = 0
    month_begins = Date.new(year, month, 1)
    month_ends = Date.new(year, month, 1).at_end_of_month
    self.movimentations.each do |movimentation|
      if (movimentation.payday >= month_begins && movimentation.payday <= month_ends && movimentation.type_of_movimentation == type)
        sum = sum + movimentation.value
      end
    end
    return sum
  end

  # ABREVIATURA DA FUNCAO sum_movimentation_by_month_and_year
  def sum_by_my(type, year, month)
    self.sum_movimentation_by_month_and_year(type, year, month)
  end
end

app/controllers/android/categories_controller.rb
class Android::CategoriesController < InheritedResources::Base
  before_filter :authenticate_user!
  
  # GET /categories.json
  def index
    user_id = params[:user_id]
    @search = Category.where("user_id = ?", user_id).search(params[:search])
    @categories = @search.all

    respond_to do |format|
      format.json
    end
  end

  # GET /categories/1.json
  def show
    user_id = params[:user_id]
    @category = Category.where("user_id = ?", user_id).find(params[:id])
    
    rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      if @category
        format.json
      else
        format.json { render :status => 200, :json=> {:status => "Failure"} }
      end
    end
  end

  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.json { render :status => 200, :json=> {:status => "Success"} }
      else
        format.json { render :status => 200, :json=> {:status => "Failure"} }
      end
    end
  end

  # GET /categories/1/edit.json
  def edit
    begin
      @category = Category.find(params[:id])
      found = true
      save = false
        save = @category.update_attributes(params[:category])
        rescue NoMethodError
    rescue ActiveRecord::RecordNotFound
      found = false
      save = false
    end

    respond_to do |format|
      if found and save
        format.json { render :status => 200, :json=> {:status => "Success"} }
      else
        format.json { render :status => 200, :json=> {:status => "Failure"} }
      end
    end
  end

  # DELETE /categories/1.json
  def destroy
    begin
      @category = Category.find(params[:id])
      found = true
      destroyed = false
        destroyed = @category.destroy
        rescue NoMethodError
    rescue ActiveRecord::RecordNotFound
      found = false
      destroyed = true
    end

    respond_to do |format|
      if found and destroyed
        format.json { render :status => 200, :json=> {:status => "Success"} }
      else
        format.json { render :status => 200, :json=> {:status => "Failure"} }
      end
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  before_filter :authenticate_user!
  
  # GET /categories
  # GET /categories.xml
  def index
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
      format.json { render :partial => "index.json" }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new
    @category.user_id = current_user.id
    @category.color = "#FFFFFF"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(categories_path, :notice => 'Nova categoria cadastrada.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(categories_path, :notice => 'Categoria Atualizada.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url, :notice => 'Categoria removida.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% stylesheet_link_tag 'colorPicker' %>
<% javascript_include_tag 'jquery.colorPicker' %>

<%= form_for(@category, :html => { :class => "form-stacked" }) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> impediram o formul&aacute;rio de ser salvo:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title, :maxlength => 20 %>
  </div>

  <div>
    <div class="input-append color" data-color="<%= @category.color %>" data-color-format="hex">
      <%= f.label :color %>
      <%= f.text_field :color, :class => "span2", :readonly => :readonly %>
    </div>
  </div>
  <div>
    <%= f.submit 'Salvar', :class => "btn" %> <%= link_to 'Cancelar', categories_path, :class => "btn btn-danger" %>
  </div>
<% end %>

<script language="javascript">
    jQuery(document).ready(function($) {
        $('#category_color').colorpicker();
    });
</script>

app/views/categories/edit.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "Categorias", categories_path + "&search[meta_sort]=title.asc" %> <span class="divider">/</span></li>
    <li class="active">Editar Categoria</li>
<% end %>

<%= render 'form' %>

<script language="javascript">
  // Destacar item de menu correspondente
  $(document).ready(function(){
     $("#menu-item-4").addClass("active");
  });
</script>

app/views/categories/index.html.erb
<%= stylesheet_link_tag 'colorPicker2' %>

<% content_for :breadcrumb do %>
    <li><a href="#">Categorias</a> <span class="divider">/</span></li>
    <li class="active">Principal</li>
<% end %>

<div class="buttons">
  <%= link_to 'Adicionar Categoria', "#myModal", :alt => 'Adicionar Categoria', :title => "Adicionar Categoria", :class => "btn btn-primary pull-right", 'data-toggle' => "modal" %>
</div>

<div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>Adicionar Categoria</h3>
  </div>
  <div class="modal-body">
    <%= render 'form' %>
  </div>
</div>


<h3>CATEGORIAS</h3>

<div class="row">
  <div class="span6">
    <p>
      Crie categorias que serão atribuidas às movimentações.
    </p>
    Abaixo você pode visualizar algumas sugestões de categorias:
    <ul>
      <li>Alimentação</li>
      <li>Transporte</li>
      <li>Saúde</li>
      <li>Aluguel</li>
      <li>Entretenimento</li>
      <li>Restaurante</li>
    </ul>
  </div>
  <div class="span6">
    <table class="table table-striped ">
      <tr>
        <th width="200" align="left"><%= sort_link @search, :title, 'Título' %></th>
        <th width="140" align="left">Cor</th>
        <th colspan="1"></th>
      </tr>

    <% @categories.each do |category| %>
      <tr onmouseover="show_button(<%= category.id %>)" onmouseout="hide_button(<%= category.id %>)">
        <td  align="left"><%= category.title.upcase %></td>
        <td  align="left"><div class="color_picker" style="background-color: <%= category.color %>"></div></td>
        <td>
          <div class="btn-action" id="<%= category.id %>">
          <%= link_to edit_category_path(category), :class => "table_line btn btn-small", 'data-placement' => "below", :rel => 'twipsy', :title => 'Editar esta movimentação' do %>
           <%= image_tag "icon-edit.gif", :align => :absmiddle, :border => 0 %>
          <% end %>
          <%= link_to category, :confirm => 'Tem certeza?', :method => :delete, :class => "table_line btn btn-small", 'data-placement' => "below", :rel => 'twipsy', :title => 'Apagar esta categoria' do %>
            <%= image_tag "icon-delete.gif", :align => :absmiddle, :border => 0 %>
          <% end %>
          </div>
      </tr>
    <% end %>
    </table>
  </div>
</div>

<br />

<%= will_paginate @categories, :prev_label => 'Anterior', :next_label => 'Próximo' %>

<script language="javascript">
  // Destacar item de menu correspondente
  $(document).ready(function(){
     $("#menu-item-4").addClass("active");
     $(".btn-action").hide();
  });

  function show_button(id) {
    $("#" + id).show();
  }

  function hide_button(id) {
    $("#" + id).hide();
  }
</script>

app/views/categories/new.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "Categorias", categories_path + "&search[meta_sort]=title.asc" %> <span class="divider">/</span></li>
    <li class="active">Nova Categoria</li>
<% end %>

<%= render 'form' %>

<script language="javascript">
  // Destacar item de menu correspondente
  $(document).ready(function(){
     $("#menu-item-4").addClass("active");
  });
</script>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>title:</b>
  <%= @category.title %>
</p>

<p>
  <b>user_id:</b>
  <%= @category.user_id %>
</p>


<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to 'Voltar', categories_path %>